"""Compatibility wrappers for older DIMACS callers.

Active product code should use ``sat_core.dimacs`` directly.
"""

from sat_core.dimacs import load_dimacs, save_dimacs


def write_dimacs_cnf(filename, clauses):
    save_dimacs(filename, clauses, ["Generated by SAT Solver"])


def read_dimacs_cnf(filename):
    return load_dimacs(filename)
